site_name: The DAO
site_description: DAO, Decentralized Autonomous Organization, 亦为“道可道, 非常道”之“道”.

theme:
  name: material
  language: zh
  palette:
    # 浅色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至暗色模式
    # 深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至亮色模式
  features:
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - tables
  - toc:
      permalink: true

docs_dir: .
